// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwZ8RKAYoXG-HK42FnxTT1fkqUH9S4vE',
    appId: '1:83805558547:web:bb65171a015181f4aeece6',
    messagingSenderId: '83805558547',
    projectId: 'costly-88e7e',
    authDomain: 'costly-88e7e.firebaseapp.com',
    storageBucket: 'costly-88e7e.firebasestorage.app',
    measurementId: 'G-WR50D8X6W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJViC4l7kWU6QuKYQRcrrpn9syTZYmbh0',
    appId: '1:83805558547:android:c1de79a8a2a0d46daeece6',
    messagingSenderId: '83805558547',
    projectId: 'costly-88e7e',
    storageBucket: 'costly-88e7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GBqXy_XK8VF0AkoaAJC9ZqolEAUaP_U',
    appId: '1:83805558547:ios:778a0976db83a2b2aeece6',
    messagingSenderId: '83805558547',
    projectId: 'costly-88e7e',
    storageBucket: 'costly-88e7e.firebasestorage.app',
    iosBundleId: 'com.example.costly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9GBqXy_XK8VF0AkoaAJC9ZqolEAUaP_U',
    appId: '1:83805558547:ios:778a0976db83a2b2aeece6',
    messagingSenderId: '83805558547',
    projectId: 'costly-88e7e',
    storageBucket: 'costly-88e7e.firebasestorage.app',
    iosBundleId: 'com.example.costly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtwZ8RKAYoXG-HK42FnxTT1fkqUH9S4vE',
    appId: '1:83805558547:web:1949bd31e9dedc93aeece6',
    messagingSenderId: '83805558547',
    projectId: 'costly-88e7e',
    authDomain: 'costly-88e7e.firebaseapp.com',
    storageBucket: 'costly-88e7e.firebasestorage.app',
    measurementId: 'G-37FJHQZ2B0',
  );
}
